change-id = 121754

[llvm]
download-ci-llvm = true

[build]
target = [
    "aarch64-unknown-hermit",
    "riscv64gc-unknown-hermit",
    "x86_64-unknown-hermit",
]

[rust]
channel = "stable"

[dist]
compression-formats = ["gz"]
